spring:
  application:
    name: 论坛系统 # 项目名称
  output:
    ansi:
      enabled: ALWAYS # 配置输出的效果

server:
  port: 58080 # 自定义的服务端口号



logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss # 日期的显示格式
  level:
    root: info # 日志的默认级别
    com.bitejiuyeke.forum: debug # 指定包下的日志级别
  file:
    path: D:/log/bit_forum # 日志保存的路径